const templateCatalog = [
    "artist_portfolio",
    "book_club",
    "coding_bootcamp",
    "community_hub",
    "creator_fan_club",
    "esports_team",
    "gaming_clan",
    "hackathon_event",
    "local_community",
    "marketplace_server",
    "music_collective",
    "nonprofit_volunteer",
    "opensource_project",
    "podcast_network",
    "roleplay_world",
    "school_classroom",
    "standard_hub",
    "startup_team",
    "streamer_community",
    "study_group",
    "support_center",
    "wellness_support"
];

const spotlightTemplates = [
    {
        label: "Built-in Template",
        name: "standard_hub",
        description: "A general-purpose launchpad with staff-only spaces, public channels, starter embeds, slowmode support, and role permissions already aligned with the current DC-Fold schema.",
        metrics: [
            { title: "Best for", value: "New community servers" },
            { title: "Includes", value: "Roles, staff corridor, general square" },
            { title: "Schema", value: "variables + roles + categories" },
            { title: "Deploy path", value: "GitHub, upload, or pasted JSON" }
        ]
    },
    {
        label: "Custom Path",
        name: "uploaded_json",
        description: "The bot supports custom JSON deployments directly through uploaded files or pasted payloads, so the web blueprint studio can feed straight into production server setup.",
        metrics: [
            { title: "Source", value: "Generated by web-app" },
            { title: "Validation", value: "Checks roles and categories first" },
            { title: "Use case", value: "Private or one-off layouts" },
            { title: "Companion feature", value: "Blueprint Studio export" }
        ]
    }
];

let spotlightIndex = 0;

let templateData = {
    variables: {
        community_name: "DevX Network",
        main_theme_color: "#7289DA"
    },
    roles: [
        { name: "Management", color: "#FF0000", hoist: true, permissions: ["administrator"] },
        {
            name: "Staff Support",
            color: "#206694",
            hoist: true,
            permissions: [
                "manage_roles",
                "manage_channels",
                "view_audit_log",
                "kick_members",
                "ban_members",
                "manage_messages",
                "move_members"
            ]
        },
        {
            name: "Community Member",
            color: "#99AAB5",
            hoist: false,
            permissions: [
                "change_nickname",
                "send_messages",
                "embed_links",
                "attach_files",
                "read_message_history",
                "add_reactions",
                "connect",
                "speak",
                "use_voice_activation"
            ]
        }
    ],
    categories: [
        {
            name: "WELCOME DESK",
            channels: [
                {
                    name: "welcome-hub",
                    type: "text",
                    requires_staff: false,
                    slowmode: 0,
                    topic: "Welcome to {{community_name}}."
                }
            ]
        },
        {
            name: "GENERAL SQUARE",
            channels: [
                {
                    name: "global-chatter",
                    type: "text",
                    requires_staff: false,
                    slowmode: 5,
                    topic: "Main conversation hub for all members."
                }
            ]
        }
    ]
};

let activeTarget = { type: "roles", catIdx: null, chanIdx: null };

function prettyTemplateName(name) {
    return name
        .split("_")
        .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
        .join(" ");
}

function renderTemplateTags() {
    const container = document.getElementById("template-tags");
    container.innerHTML = templateCatalog
        .map((template) => `<span class="template-tag">${prettyTemplateName(template)}</span>`)
        .join("");
}

function renderTemplateSpotlight() {
    const target = document.getElementById("template-spotlight");
    const item = spotlightTemplates[spotlightIndex];

    target.innerHTML = `
        <div class="spotlight-copy">
            <span class="spotlight-label">${item.label}</span>
            <h3>${prettyTemplateName(item.name)}</h3>
            <p>${item.description}</p>
        </div>
        <div class="spotlight-columns">
            ${item.metrics
                .map(
                    (metric) => `
                        <div class="spotlight-metric">
                            <strong>${metric.title}</strong>
                            <span>${metric.value}</span>
                        </div>
                    `
                )
                .join("")}
        </div>
    `;
}

function rotateSpotlight() {
    spotlightIndex = (spotlightIndex + 1) % spotlightTemplates.length;
    renderTemplateSpotlight();
}

function syncMenuState() {
    const toggle = document.getElementById("menu-toggle");
    const menu = document.getElementById("site-menu");

    toggle.addEventListener("click", () => {
        const isOpen = menu.classList.toggle("open");
        toggle.setAttribute("aria-expanded", String(isOpen));
    });

    menu.querySelectorAll("a").forEach((link) => {
        link.addEventListener("click", () => {
            menu.classList.remove("open");
            toggle.setAttribute("aria-expanded", "false");
        });
    });
}

function renderSidebarTree() {
    const container = document.getElementById("sidebar-layout-tree");
    container.innerHTML = "";

    templateData.categories.forEach((category, catIdx) => {
        const catBlock = document.createElement("div");
        catBlock.className = "category-block";

        const categoryHeader = document.createElement("div");
        categoryHeader.className = "category-header";
        categoryHeader.innerHTML = `
            <span>${category.name}</span>
            <button class="add-chan-btn" type="button" aria-label="Add channel">+</button>
        `;

        const addChannelButton = categoryHeader.querySelector(".add-chan-btn");
        addChannelButton.addEventListener("click", (event) => openInlineChannelCreator(catIdx, event));

        const channelsContainer = document.createElement("div");
        channelsContainer.className = "category-channels";

        category.channels.forEach((channel, chanIdx) => {
            const chanItem = document.createElement("button");
            const isActive =
                activeTarget.type === "channel" &&
                activeTarget.catIdx === catIdx &&
                activeTarget.chanIdx === chanIdx;

            chanItem.className = `tree-item ${isActive ? "active" : ""}`;
            chanItem.type = "button";
            chanItem.textContent = `${channel.type === "text" ? "TXT" : "VOC"}  ${channel.name}`;
            chanItem.addEventListener("click", () => switchView("channel", catIdx, chanIdx));
            channelsContainer.appendChild(chanItem);
        });

        catBlock.appendChild(categoryHeader);
        catBlock.appendChild(channelsContainer);
        container.appendChild(catBlock);
    });
}

function updateJSONPreview() {
    document.getElementById("json-preview").textContent = JSON.stringify(templateData, null, 2);
}

function switchView(viewType, catIdx = null, chanIdx = null) {
    activeTarget = { type: viewType, catIdx, chanIdx };

    const rolesView = document.getElementById("view-roles");
    const channelView = document.getElementById("view-channel");
    const rolesMenu = document.getElementById("roles-menu-item");

    rolesView.classList.toggle("hidden", viewType !== "roles");
    channelView.classList.toggle("hidden", viewType !== "channel");
    rolesMenu.classList.toggle("active", viewType === "roles");

    if (viewType === "roles") {
        document.getElementById("view-icon").textContent = "RL";
        document.getElementById("view-title").textContent = "Server Roles Matrix Configuration";
    } else {
        const chan = templateData.categories[catIdx].channels[chanIdx];
        document.getElementById("view-icon").textContent = chan.type === "text" ? "TXT" : "VOC";
        document.getElementById("view-title").textContent = `Configuring Channel: #${chan.name}`;
        document.getElementById("chan-name").value = chan.name;
        document.getElementById("chan-type").value = chan.type;
        document.getElementById("chan-slowmode").value = chan.slowmode || 0;
        document.getElementById("chan-staff").checked = chan.requires_staff || false;
        document.getElementById("chan-topic").value = chan.topic || "";
    }

    renderSidebarTree();
}

function inferRoleConfig(name) {
    const normalized = name.toLowerCase();

    if (normalized.includes("admin") || normalized.includes("owner") || normalized.includes("management")) {
        return {
            color: "#FF0000",
            hoist: true,
            permissions: ["administrator"]
        };
    }

    if (normalized.includes("staff") || normalized.includes("mod") || normalized.includes("support")) {
        return {
            color: "#206694",
            hoist: true,
            permissions: [
                "manage_roles",
                "manage_channels",
                "view_audit_log",
                "kick_members",
                "ban_members",
                "manage_messages",
                "move_members"
            ]
        };
    }

    return {
        color: "#99AAB5",
        hoist: false,
        permissions: [
            "change_nickname",
            "send_messages",
            "embed_links",
            "attach_files",
            "read_message_history",
            "add_reactions",
            "connect",
            "speak",
            "use_voice_activation"
        ]
    };
}

function saveRolesState() {
    const rolesInput = document.getElementById("role-names").value;
    templateData.roles = rolesInput
        .split(",")
        .map((roleName) => roleName.trim())
        .filter((roleName) => roleName.length > 0)
        .map((roleName) => ({
            name: roleName,
            ...inferRoleConfig(roleName)
        }));

    updateJSONPreview();
}

function updateActiveElementData() {
    if (activeTarget.type !== "channel") {
        return;
    }

    const { catIdx, chanIdx } = activeTarget;
    const chan = templateData.categories[catIdx].channels[chanIdx];
    chan.name = document.getElementById("chan-name").value.trim().toLowerCase().replace(/\s+/g, "-");
    chan.type = document.getElementById("chan-type").value;
    chan.slowmode = parseInt(document.getElementById("chan-slowmode").value, 10) || 0;
    chan.requires_staff = document.getElementById("chan-staff").checked;
    chan.topic = document.getElementById("chan-topic").value;

    renderSidebarTree();
    updateJSONPreview();
}

function toggleCategoryCreator(show) {
    document.getElementById("inline-category-creator").classList.toggle("hidden", !show);
    if (show) {
        document.getElementById("new-cat-name").focus();
        toggleChannelCreator(false);
    }
}

function toggleChannelCreator(show) {
    document.getElementById("inline-channel-creator").classList.toggle("hidden", !show);
}

function confirmCategoryCreate() {
    const nameInput = document.getElementById("new-cat-name");
    const name = nameInput.value.trim();

    if (!name) {
        return;
    }

    templateData.categories.push({ name: name.toUpperCase(), channels: [] });
    nameInput.value = "";
    toggleCategoryCreator(false);
    renderSidebarTree();
    updateJSONPreview();
}

function openInlineChannelCreator(catIdx, event) {
    if (event) {
        event.stopPropagation();
    }

    document.getElementById("new-chan-target-cat").value = String(catIdx);
    toggleCategoryCreator(false);
    toggleChannelCreator(true);
    document.getElementById("new-chan-name").focus();
}

function confirmChannelCreate() {
    const nameInput = document.getElementById("new-chan-name");
    const catIdx = parseInt(document.getElementById("new-chan-target-cat").value, 10);
    const name = nameInput.value.trim();

    if (!name || Number.isNaN(catIdx)) {
        return;
    }

    const formattedName = name.toLowerCase().replace(/\s+/g, "-");
    templateData.categories[catIdx].channels.push({
        name: formattedName,
        type: "text",
        requires_staff: false,
        slowmode: 0,
        topic: ""
    });

    nameInput.value = "";
    toggleChannelCreator(false);
    switchView("channel", catIdx, templateData.categories[catIdx].channels.length - 1);
    updateJSONPreview();
}

async function copyTemplateJSON() {
    saveRolesState();
    const button = document.getElementById("copy-json-btn");
    const originalText = button.textContent;

    try {
        await navigator.clipboard.writeText(JSON.stringify(templateData, null, 2));
        button.textContent = "Copied";
        setTimeout(() => {
            button.textContent = originalText;
        }, 1800);
    } catch (error) {
        window.alert(`Clipboard copy failed: ${error}`);
    }
}

function exportTemplateJSON() {
    saveRolesState();
    const dataStr = `data:text/json;charset=utf-8,${encodeURIComponent(JSON.stringify(templateData, null, 2))}`;
    const downloadAnchor = document.createElement("a");
    downloadAnchor.setAttribute("href", dataStr);
    downloadAnchor.setAttribute("download", "custom_hub_template.json");
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
}

function bindStudioEvents() {
    document.getElementById("roles-menu-item").addEventListener("click", () => switchView("roles"));
    document.getElementById("role-names").addEventListener("input", saveRolesState);

    document.getElementById("chan-name").addEventListener("input", updateActiveElementData);
    document.getElementById("chan-type").addEventListener("change", updateActiveElementData);
    document.getElementById("chan-slowmode").addEventListener("input", updateActiveElementData);
    document.getElementById("chan-staff").addEventListener("change", updateActiveElementData);
    document.getElementById("chan-topic").addEventListener("input", updateActiveElementData);

    document.getElementById("add-category-btn").addEventListener("click", () => toggleCategoryCreator(true));
    document.getElementById("confirm-category-btn").addEventListener("click", confirmCategoryCreate);
    document.getElementById("cancel-category-btn").addEventListener("click", () => toggleCategoryCreator(false));
    document.getElementById("confirm-channel-btn").addEventListener("click", confirmChannelCreate);
    document.getElementById("cancel-channel-btn").addEventListener("click", () => toggleChannelCreator(false));
    document.getElementById("copy-json-btn").addEventListener("click", copyTemplateJSON);
    document.getElementById("download-json-btn").addEventListener("click", exportTemplateJSON);
}

function initializePage() {
    syncMenuState();
    renderTemplateTags();
    renderTemplateSpotlight();
    setInterval(rotateSpotlight, 4200);
    bindStudioEvents();
    renderSidebarTree();
    updateJSONPreview();
    switchView("roles");
}

initializePage();
